 name: CI Test


on:
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
    - '*.md'
  push:
    branches:
      - main
      - dev
  paths-ignore:
    - '*.md'

  jobs:
    build:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
          name:  Setup JDK
        - uses:  actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'zulu'
            cache: gradle



        - name: Google-Service-Json
          run: echo "${{ secrets.secret }}" | base64 --decode > app/google-services.json

        - name: Dependencies list
          run: ./gradlew :app:androidDependencies


        - name: Build gradle
          run: ./gradlew build